package com.example.bankcards.entity;

public enum ErrorCode {
    E_CARD_EXPIRED,
    E_CARD_NOT_IN_BLOCK_REQUEST_STATUS,
    E_USER_NOT_FOUND,
    E_CARD_BALANCE_ACCESS_DENIED,
    E_CARD_BLOCK_REQUEST_ACCESS_DENIED,
    E_CARD_ALREADY_BLOCKED,
    E_CARD_BLOCK_REQUEST_ALREADY_SENT,
    E_USERNAME_TAKEN_BY_ANOTHER_USER,
    E_CARD_NOT_FOUND,
    E_CARD_ALREADY_ACTIVE,
}
